/* =====================================================================
   data.js — Toutes les données du voyage, codées en dur.
   Objet global TRIP_DATA chargé directement (aucun fetch, aucun backend).
   ===================================================================== */

const REGIONS = {
  city:     { label: "Ville & culture",  color: "#C45A32", light: "#FBEAE1" },
  coffee:   { label: "Région du café",   color: "#3F8050", light: "#E6F1E8" },
  jungle:   { label: "Parc & jungle",    color: "#2C6F5D", light: "#E1EDE9" },
  carib:    { label: "Bord de mer",      color: "#1D8AAC", light: "#DEF0F5" },
  colonial: { label: "Ville coloniale",  color: "#BF8A2C", light: "#F6EBD2" },
};

const EFFORT = {
  calm:     { label: "Journée calme",    dots: "●",     color: "#7AA86A" },
  moderate: { label: "Effort modéré",    dots: "● ●",   color: "#E0A83D" },
  sporty:   { label: "Journée sportive", dots: "● ● ●", color: "#CF6A3F" },
};

/* Chaque jour :
   {
     id, dateLabel, isoDate, place, region, effort,
     summary, detail, transportNote, transportDetail,
     transportDuration, transportCost,
     accommodation, accommodationLink, accommodationPrice,
     whyThisStep, practicalWarning (ou null)
   } */
const TRIP_DAYS = [
  {
    id: 1,
    dateLabel: "mer. 13 août",
    isoDate: "2025-08-13",
    place: "Medellín",
    region: "city",
    effort: "calm",
    summary: "Arrivée à 16h40. On dépose les sacs à El Poblado, dîner local et repos après le vol.",
    detail: "Votre avion se pose à Medellín à 16h40. Vous prenez un taxi ou un Uber jusqu'à votre logement, dans le quartier El Poblado ou Laureles (calmes, sûrs et agréables le soir). Vous posez vos sacs, vous allez manger un plat local tout près, puis vous vous reposez. On ne fait rien de fatigant le premier soir, parce que le voyage en avion est déjà long.",
    transportNote: "Sur place · nuit à Medellín",
    transportDetail: "Pas de trajet aujourd'hui. Vous restez dormir à Medellín, et vous y dormirez les trois premières nuits : vous ne défaites vos sacs qu'une seule fois.",
    transportDuration: "Aucun trajet",
    transportCost: "Aucun coût",
    accommodation: "Une auberge (hostal) avec chambre privée, ou un petit hôtel simple à El Poblado.",
    accommodationLink: "https://www.booking.com/city/co/medellin.html",
    accommodationPrice: "25 à 40 €",
    whyThisStep: "Medellín est le point de départ du voyage, là où votre avion atterrit. On commence doucement pour récupérer du vol.",
    practicalWarning: null,
  },
  {
    id: 2,
    dateLabel: "jeu. 14 août",
    isoDate: "2025-08-14",
    place: "Medellín",
    region: "city",
    effort: "moderate",
    summary: "Comuna 13 et ses fresques le matin, téléphérique au-dessus de la ville, Plaza Botero en soirée.",
    detail: "Grande journée de visite. Le matin, la Comuna 13 : un quartier autrefois très dangereux, aujourd'hui couvert de fresques colorées, avec de la musique et des escaliers roulants en plein air. Un guide local peut vous raconter l'histoire. L'après-midi, le métro puis le téléphérique (un petit wagon suspendu dans les airs) qui monte au-dessus de la ville. Le soir, la Plaza Botero et ses grosses statues rondes.",
    transportNote: "Sur place · métro + câble (~1 €)",
    transportDetail: "Pas de trajet entre villes. Vous bougez dans Medellín avec le métro et le téléphérique, faciles et bon marché. Vous dormez encore à Medellín.",
    transportDuration: "Déplacements courts dans la ville",
    transportCost: "Métro et téléphérique : environ 1 € le trajet",
    accommodation: "Le même logement que la veille, vous ne changez pas.",
    accommodationLink: "https://www.booking.com/city/co/medellin.html",
    accommodationPrice: "25 à 40 €",
    whyThisStep: "Medellín raconte une belle histoire : une ville qui a changé en mieux. Le téléphérique et la Comuna 13 sont les deux choses à ne pas manquer.",
    practicalWarning: null,
  },
  {
    id: 3,
    dateLabel: "ven. 15 août",
    isoDate: "2025-08-15",
    place: "Guatapé (matinée)",
    region: "city",
    effort: "moderate",
    summary: "Départ à l'aube. Les 740 marches du rocher El Peñol avant la foule, puis le village coloré. Retour en début d'après-midi ; fin de journée libre à Medellín.",
    detail: "Sortie à Guatapé, concentrée sur la matinée. Levez-vous tôt : les bus partent toutes les 30 minutes dès 5h30, et partir à l'aube vous fait grimper le rocher avant la foule et avant la grosse chaleur. Vous montez les 740 marches de la Piedra del Peñol (doucement, avec des pauses) et découvrez la vue sur les lacs bleus en forme de bras. Ensuite, promenade dans le village de Guatapé, le plus coloré du pays. Retour à Medellín en début d'après-midi. L'après-midi est libre : repos, derniers achats, et surtout préparation des sacs pour le grand trajet de demain.",
    transportNote: "Bus aller-retour · 2 h + 2 h · 5–7 € · retour dormir à Medellín",
    transportDetail: "Le matin très tôt, métro jusqu'à la station Caribe puis Terminal du Nord (ou taxi/Uber). Bus pour Guatapé, départs très fréquents. Achetez votre billet de retour dès l'arrivée à Guatapé, au bureau situé sur la rue principale, pour être sûres d'avoir une place. Rentrer en début d'après-midi vous évite les embouteillages de fin de journée.",
    transportDuration: "Environ 2 heures à l'aller, 2 heures au retour",
    transportCost: "Environ 5 à 7 € l'aller-retour en bus",
    accommodation: "Vous revenez dormir à Medellín, dans le même logement (3e et dernière nuit).",
    accommodationLink: "https://www.booking.com/city/co/medellin.html",
    accommodationPrice: "25 à 40 €",
    whyThisStep: "Une sortie qui vaut vraiment le détour, faite en demi-journée pour garder de l'énergie. L'après-midi libre permet d'aborder le long trajet de demain reposées.",
    practicalWarning: "Rocher fermé et dernier bus vers 19h — ne pas viser le coucher de soleil sur place.",
  },
  {
    id: 4,
    dateLabel: "sam. 16 août",
    isoDate: "2025-08-16",
    place: "Medellín → Salento (par avion, via Armenia)",
    region: "coffee",
    effort: "moderate",
    summary: "Vol Medellín → Armenia (~1 h) puis bus jusqu'à Salento · 5–6 h porte à porte · 80–100 €",
    detail: "Grand trajet vers la région du café, en avion. Vol Medellín → Armenia (AXM), environ 1 heure. Vérifiez impérativement que le vol est DIRECT : certains passent par Bogotá, ce qui annulerait tout le gain de temps. À l'arrivée à Armenia, taxi jusqu'au terminal de bus, puis bus jusqu'à Salento (départs toutes les 20 minutes, environ 50 minutes). Vous arrivez à Salento en fin d'après-midi. Village coloré et tranquille au milieu des plantations de café ; installation et soirée calme.",
    transportNote: "Vol + bus · 5–6 h porte à porte · 80–100 €",
    transportDetail: "Étape par étape : 1) taxi ou Uber depuis votre logement à Medellín jusqu'à l'aéroport José María Córdova (~45 min) ; 2) vol vers Armenia (AXM), environ 1 h, DIRECT de préférence ; 3) à l'arrivée à Armenia, taxi jusqu'au Terminal de Transportes de Armenia ; 4) bus local jusqu'à Salento, départs toutes les 20 minutes. Réservez le vol à l'avance pour un meilleur tarif.",
    transportDuration: "Environ 5 à 6 heures porte à porte",
    transportCost: "Environ 80 à 100 € par personne (vol + taxi + bus)",
    accommodation: "Une auberge ou un petit hôtel simple dans le centre de Salento.",
    accommodationLink: "https://www.avianca.com/",
    accommodationPrice: "20 à 35 €",
    whyThisStep: "Salento est la meilleure base pour la vallée de Cocora et les fermes de café. L'avion réduit le temps de trajet par rapport au bus, pour un confort supérieur.",
    practicalWarning: "Vérifiez que le vol Medellín → Armenia est direct (pas d'escale à Bogotá).",
  },
  {
    id: 5,
    dateLabel: "dim. 17 août",
    isoDate: "2025-08-17",
    place: "Vallée de Cocora",
    region: "coffee",
    effort: "sporty",
    summary: "Jeep Willys puis randonnée parmi les palmiers de cire géants. L'après-midi, ferme de café.",
    detail: "Le matin, vous montez dans une vieille jeep colorée (une Willys) sur la place du village, direction la vallée de Cocora. Randonnée d'environ cinq heures au milieu des palmiers de cire, les plus hauts du monde et arbre symbole de la Colombie. Marche de niveau moyen, parfois boueuse : bonnes chaussures indispensables. L'après-midi, visite d'une ferme de café (finca) avec explication et dégustation.",
    transportNote: "Jeep Willys aller-retour · nuit à Salento",
    transportDetail: "Jeep Willys depuis la place de Salento, et la même jeep vous ramène. Vous ne changez pas de logement. Ce soir, préparez vos sacs : demain matin, départ vers l'aéroport de Pereira.",
    transportDuration: "Environ 30 minutes de jeep pour rejoindre la vallée",
    transportCost: "Environ 3 à 4 € l'aller-retour en jeep",
    accommodation: "Le même logement qu'à Salento.",
    accommodationLink: "https://www.booking.com/city/co/salento.html",
    accommodationPrice: "20 à 35 €",
    whyThisStep: "C'est le grand moment nature et randonnée du voyage. Les palmiers géants sont un spectacle qu'on ne voit nulle part ailleurs.",
    practicalWarning: "Bonnes chaussures indispensables, terrain parfois boueux.",
  },
  {
    id: 6,
    dateLabel: "lun. 18 août",
    isoDate: "2025-08-18",
    place: "Santa Marta",
    region: "carib",
    effort: "moderate",
    summary: "Le grand saut vers la mer : route vers Pereira puis vol. Arrivée sur la côte, première soirée au bord de l'eau.",
    detail: "Vous traversez le pays pour rejoindre la côte caraïbe. Route jusqu'à l'aéroport de Pereira, puis vol (souvent avec une courte escale) jusqu'à Santa Marta. En arrivant, le climat change du tout au tout : chaleur, air tropical, odeur de mer. Installation et première soirée au bord de l'eau.",
    transportNote: "Route + vol · 2–4 h · 50–80 €",
    transportDetail: "Étape par étape : 1) taxi ou bus partagé de Salento à l'aéroport de Pereira (environ 1 h) ; 2) vol jusqu'à Santa Marta. Un taxi vous conduit ensuite à votre logement.",
    transportDuration: "Environ 2 à 4 heures en tout (avec l'escale)",
    transportCost: "Entre 50 et 80 € le vol, réservé à l'avance",
    accommodation: "Une auberge ou un petit hôtel dans le centre de Santa Marta.",
    accommodationLink: "https://www.booking.com/city/co/santa-marta.html",
    accommodationPrice: "25 à 40 €",
    whyThisStep: "L'avion fait gagner presque une journée entière par rapport au bus de nuit, pour un prix comparable.",
    practicalWarning: null,
  },
  {
    id: 7,
    dateLabel: "mar. 19 août",
    isoDate: "2025-08-19",
    place: "Minca (une nuit)",
    region: "jungle",
    effort: "moderate",
    summary: "Montée dans la jungle de la Sierra Nevada. Cascades où se baigner, ferme de cacao, coucher de soleil au mirador.",
    detail: "Vous montez à Minca, village posé dans la jungle sur les pentes de la Sierra Nevada, où il fait plus frais qu'au bord de la mer. Au programme : cascades où l'on se baigne (Marinka, Pozo Azul), visite d'une ferme de café ou de cacao, et coucher de soleil depuis un mirador en hauteur. Une seule nuit ici : c'est assez pour goûter l'ambiance sans y passer trop de temps.",
    transportNote: "Colectivo · 45 min · nuit à Minca",
    transportDetail: "Colectivo (petit van partagé) depuis le marché public de Santa Marta, montée d'environ 45 minutes. Départs fréquents dans la journée. Demain matin, vous redescendez pour rejoindre le parc Tayrona.",
    transportDuration: "Environ 45 minutes de montée",
    transportCost: "Environ 3 € le trajet",
    accommodation: "Une auberge à Minca avec vue sur la jungle.",
    accommodationLink: "https://www.booking.com/city/co/minca.html",
    accommodationPrice: "20 à 35 €",
    whyThisStep: "Contraste immédiat avec la mer : montagne, fraîcheur et jungle. Une nuit suffit pour en profiter avant de consacrer plus de temps au Tayrona.",
    practicalWarning: null,
  },
  {
    id: 8,
    dateLabel: "mer. 20 août",
    isoDate: "2025-08-20",
    place: "Parc Tayrona (arrivée éco-lodge)",
    region: "jungle",
    effort: "sporty",
    summary: "Entrée par El Zaino et installation à l'éco-lodge. Marche en forêt jusqu'aux premières plages, premier bain.",
    detail: "Cap sur le plus beau parc de la côte, là où la jungle rejoint la mer. Vous entrez par la porte El Zaino et vous installez dans un éco-lodge, ce qui vous évite de porter vos sacs pendant des heures et de dormir en hamac. Une fois délestées, vous partez marcher dans le parc : sentier en forêt vers les premières plages (Arrecifes, La Piscina), premier bain et découverte des lieux.",
    transportNote: "Colectivo + bus · 45 + 45 min · ~6 € + entrée ~20 €",
    transportDetail: "Étape par étape : 1) colectivo de Minca pour redescendre à Santa Marta ; 2) au marché public, bus jusqu'à l'entrée El Zaino du Tayrona ; 3) paiement de l'entrée, puis installation à l'éco-lodge avant de partir marcher.",
    transportDuration: "45 min + 45 min de bus, puis marche dans le parc",
    transportCost: "Environ 6 € de transports, plus environ 20 € l'entrée du parc",
    accommodation: "Éco-lodge ou cabane confortable dans le parc / près de l'entrée El Zaino (2 nuits).",
    accommodationLink: "https://www.booking.com/searchresults.fr.html?ss=Tayrona",
    accommodationPrice: "30 à 55 €",
    whyThisStep: "Deux nuits en éco-lodge donnent deux journées pleines dans le parc, tout en dormant confortablement.",
    practicalWarning: "Aucun distributeur d'argent dans le parc : prenez du liquide avant d'entrer.",
  },
  {
    id: 9,
    dateLabel: "jeu. 21 août",
    isoDate: "2025-08-21",
    place: "Parc Tayrona (journée pleine)",
    region: "jungle",
    effort: "moderate",
    summary: "Journée pleine dans le parc, tôt le matin avant la foule. Cabo San Juan, snorkeling à La Piscina, criques plus calmes au-delà.",
    detail: "La récompense de dormir sur place : avant 10 h, le parc est presque désert, les visiteurs à la journée n'étant pas encore arrivés. Vous marchez jusqu'à Cabo San Juan, la plage emblématique entre deux rochers, pour un bain au calme. Puis snorkeling à La Piscina, une crique protégée idéale pour observer les poissons. En continuant à pied, vous trouverez des plages nettement plus tranquilles.",
    transportNote: "À pied dans le parc · nuit à l'éco-lodge",
    transportDetail: "Déplacements uniquement à pied dans le parc, sans les sacs. Vous rentrez dormir au même éco-lodge (2e nuit).",
    transportDuration: "Marche à la journée dans le parc",
    transportCost: "Pas de transport payant (entrée déjà réglée)",
    accommodation: "Le même éco-lodge que la veille.",
    accommodationLink: "https://www.booking.com/searchresults.fr.html?ss=Tayrona",
    accommodationPrice: "30 à 55 €",
    whyThisStep: "Une deuxième journée permet de voir les plus belles criques, de faire du snorkeling et de profiter du parc au calme.",
    practicalWarning: "Baignade uniquement sur les plages autorisées : courants dangereux ailleurs.",
  },
  {
    id: 10,
    dateLabel: "ven. 22 août",
    isoDate: "2025-08-22",
    place: "Palomino",
    region: "carib",
    effort: "moderate",
    summary: "Village de plage bohème. Descente de la rivière en bouée depuis la Sierra, longue plage sauvage, coucher de soleil.",
    detail: "Petit village de bord de mer à l'ambiance décontractée, avec une longue plage sauvage. L'activité phare : la descente de la rivière en bouée (tubing), qui part de la Sierra et se termine près de la mer, entre jungle et montagne. Fin de journée sur la plage pour le coucher de soleil.",
    transportNote: "Bus local · ~1 h · nuit à Palomino",
    transportDetail: "Bus local depuis la route principale près d'El Zaino, direction l'est, jusqu'à Palomino. Ils passent régulièrement, on les arrête au bord de la route.",
    transportDuration: "Environ 1 heure de bus",
    transportCost: "Environ 3 € le trajet",
    accommodation: "Auberge ou cabane en bord de plage à Palomino.",
    accommodationLink: "https://www.booking.com/searchresults.fr.html?ss=Palomino",
    accommodationPrice: "25 à 45 €",
    whyThisStep: "Cette étape prolonge le temps sur la côte caraïbe, avec une activité nature différente de la randonnée.",
    practicalWarning: "Courants marins forts : baignade avec prudence.",
  },
  {
    id: 11,
    dateLabel: "sam. 23 août",
    isoDate: "2025-08-23",
    place: "Retour à Santa Marta",
    region: "carib",
    effort: "moderate",
    summary: "Matinée plage à Palomino, retour vers Santa Marta. Soir : centre historique, Parque de los Novios, ceviche.",
    detail: "Matinée tranquille sur la plage de Palomino, puis retour vers Santa Marta. L'après-midi, installation et découverte du centre historique. Le soir, promenade sur le Parque de los Novios, très animé, et dégustation d'un ceviche (poisson frais mariné).",
    transportNote: "Bus local · ~2 h · nuit à Santa Marta",
    transportDetail: "Bus local Palomino → Santa Marta, sur la route principale. Ce soir, préparez le départ : demain, navette pour Carthagène.",
    transportDuration: "Environ 2 heures de bus",
    transportCost: "Environ 5 € le trajet",
    accommodation: "Une auberge ou un petit hôtel dans le centre de Santa Marta.",
    accommodationLink: "https://www.booking.com/city/co/santa-marta.html",
    accommodationPrice: "25 à 40 €",
    whyThisStep: "Étape logique de transition : on regroupe les affaires en ville avant le dernier grand trajet vers Carthagène.",
    practicalWarning: null,
  },
  {
    id: 12,
    dateLabel: "dim. 24 août",
    isoDate: "2025-08-24",
    place: "Carthagène (arrivée)",
    region: "colonial",
    effort: "moderate",
    summary: "Navette porte-à-porte vers la ville coloniale ; premières ruelles de la vieille ville l'après-midi.",
    detail: "Vous rejoignez Carthagène, la plus belle ville coloniale du pays, ceinte de remparts de pierre. Le plus pratique est la navette partagée, qui vient vous chercher près de votre logement. Arrivée l'après-midi et premières promenades dans les ruelles de la vieille ville.",
    transportNote: "Navette partagée · 4–5 h · 16–22 €",
    transportDetail: "Navette partagée (compagnies Marsol ou Berlinas). Avantage : prise en charge près de l'hôtel et dépose près de votre logement, sans passer par les gares routières éloignées du centre.",
    transportDuration: "Entre 4 et 5 heures",
    transportCost: "Entre 16 et 22 € (environ 70 000 pesos)",
    accommodation: "Une auberge dans le quartier de Getsemaní, central et animé.",
    accommodationLink: "https://www.booking.com/city/co/cartagena-de-indias.html",
    accommodationPrice: "30 à 50 €",
    whyThisStep: "On garde la plus belle ville pour la fin, et c'est de là que part votre vol retour.",
    practicalWarning: null,
  },
  {
    id: 13,
    dateLabel: "lun. 25 août",
    isoDate: "2025-08-25",
    place: "Carthagène",
    region: "colonial",
    effort: "moderate",
    summary: "Vieille ville fortifiée, château San Felipe, Getsemaní, coucher de soleil sur les remparts. Îles Rosario en option.",
    detail: "Journée complète à Carthagène. Promenade dans la vieille ville fortifiée, entre balcons fleuris et petites places ombragées. Visite du château San Felipe, forteresse imposante. Flânerie dans Getsemaní, quartier bohème couvert de fresques. En fin de journée, coucher de soleil depuis les remparts. Option : demi-journée en bateau vers les îles Rosario, aux eaux turquoise.",
    transportNote: "À pied · nuit à Getsemaní",
    transportDetail: "Pas de trajet entre villes : tout se fait à pied dans Carthagène. Vous dormez au même endroit.",
    transportDuration: "Déplacements à pied",
    transportCost: "Îles Rosario en option : 25 à 40 €",
    accommodation: "Le même logement à Getsemaní.",
    accommodationLink: "https://www.booking.com/city/co/cartagena-de-indias.html",
    accommodationPrice: "30 à 50 €",
    whyThisStep: "C'est le grand moment culturel du voyage, gardé pour la fin, juste avant le départ.",
    practicalWarning: null,
  },
  {
    id: 14,
    dateLabel: "mar. 26 août",
    isoDate: "2025-08-26",
    place: "Départ",
    region: "colonial",
    effort: "calm",
    summary: "Dernier petit-déjeuner à Getsemaní, souvenirs, transfert. Aéroport à 10 min du centre.",
    detail: "Dernier jour. Selon l'heure de votre vol : petit-déjeuner à Getsemaní, derniers achats de souvenirs, puis transfert. L'aéroport de Carthagène est à environ dix minutes du centre, donc pas de stress pour le départ.",
    transportNote: "Taxi vers l'aéroport (CTG) · ~15 min",
    transportDetail: "Taxi ou Uber depuis votre logement jusqu'à l'aéroport de Carthagène (code CTG).",
    transportDuration: "Environ 15 minutes",
    transportCost: "Environ 4 à 6 € le taxi",
    accommodation: "Pas de logement ce soir, c'est le jour du départ.",
    accommodationLink: null,
    accommodationPrice: "Aucun",
    whyThisStep: "C'est le jour prévu de votre vol retour depuis Carthagène. On termine sans précipitation.",
    practicalWarning: null,
  },
];

/* Chaque trajet :
   { id, title, howAndWhy, duration, cost, alternative, whyNotAlternative, bookingPlatform, bookingURL (ou null) } */
const TRANSPORT_LEGS = [
  {
    id: 1,
    title: "Medellín → Guatapé (matinée)",
    howAndWhy: "Bus depuis le Terminal du Nord (métro station Caribe). Départs toutes les 30 minutes dès 5h30. Achetez le billet retour dès l'arrivée à Guatapé, au bureau de la rue principale.",
    duration: "2 h à l'aller, 2 h au retour",
    cost: "5 à 7 € l'aller-retour",
    alternative: "Y rester la journée entière ou dormir sur place",
    whyNotAlternative: "En demi-journée vous voyez l'essentiel et vous rentrez avant les embouteillages, avec un après-midi libre pour préparer le trajet du lendemain.",
    bookingPlatform: "redBus",
    bookingURL: "https://www.redbus.co/",
  },
  {
    id: 2,
    title: "Medellín → Salento (en avion, via Armenia)",
    howAndWhy: "Vol Medellín → Armenia (AXM), environ 1 h — vérifiez qu'il est DIRECT. Puis taxi jusqu'au terminal de bus d'Armenia, puis bus jusqu'à Salento (départs toutes les 20 min, ~50 min).",
    duration: "5 à 6 heures porte à porte",
    cost: "80 à 100 € tout compris",
    alternative: "Le bus direct Flota Occidental (Terminal del Sur, 9h00 → 16h00, ~21 €)",
    whyNotAlternative: "Le bus reste nettement moins cher, mais l'avion est plus rapide et plus confortable pour ce trajet en une seule journée avec plusieurs étapes de montagne. Choix retenu pour le confort.",
    bookingPlatform: "Avianca (vérifier vol direct)",
    bookingURL: "https://www.avianca.com/",
  },
  {
    id: 3,
    title: "Salento → Santa Marta (le grand saut)",
    howAndWhy: "Route jusqu'à l'aéroport de Pereira, puis vol vers Santa Marta.",
    duration: "2 à 4 heures avec l'escale",
    cost: "50 à 80 €",
    alternative: "Bus de nuit de 16 à 18 heures",
    whyNotAlternative: "Le bus coûterait à peine moins cher pour une nuit entière plus une journée en moins de confort. L'avion libère un jour complet pour la côte caraïbe.",
    bookingPlatform: "Avianca / Wingo / JetSmart (comparer)",
    bookingURL: "https://www.avianca.com/",
  },
  {
    id: 4,
    title: "Santa Marta → Minca",
    howAndWhy: "Colectivo depuis le marché public, départs fréquents, pas de réservation.",
    duration: "45 minutes",
    cost: "Environ 3 €",
    alternative: "Taxi privé",
    whyNotAlternative: "Bien plus cher pour exactement le même trajet.",
    bookingPlatform: "Sur place, au marché public",
    bookingURL: null,
  },
  {
    id: 5,
    title: "Minca → parc Tayrona (entrée El Zaino)",
    howAndWhy: "Colectivo pour redescendre à Santa Marta, puis bus local vers l'entrée El Zaino.",
    duration: "45 min + 45 min",
    cost: "Environ 6 € au total",
    alternative: "Navette privée depuis l'hôtel",
    whyNotAlternative: "Nettement plus chère sans réel gain de temps. Prévoyez du liquide, pas de distributeur au parc.",
    bookingPlatform: "Sur place (bus local au marché public)",
    bookingURL: "https://www.bookaway.com/s/santa-marta-colombia",
  },
  {
    id: 6,
    title: "Tayrona → Palomino",
    howAndWhy: "Bus local sur la route principale, direction est, on l'arrête au bord de la route.",
    duration: "Environ 1 heure",
    cost: "Environ 3 €",
    alternative: "Taxi",
    whyNotAlternative: "Le bus est bien moins cher et passe très régulièrement sur cet axe.",
    bookingPlatform: "Sur place (billet à bord)",
    bookingURL: null,
  },
  {
    id: 7,
    title: "Palomino → Santa Marta",
    howAndWhy: "Bus local sur la route principale, trajet direct et fréquent.",
    duration: "Environ 2 heures",
    cost: "Environ 5 €",
    alternative: "Navette privée",
    whyNotAlternative: "Plus chère, sans avantage réel sur un trajet aussi simple.",
    bookingPlatform: "Sur place ou Bookaway",
    bookingURL: "https://www.bookaway.com/routes/colombia/palomino-to-santa-marta",
  },
  {
    id: 8,
    title: "Santa Marta → Carthagène",
    howAndWhy: "Navette partagée (Marsol ou Berlinas), prise en charge et dépose près des logements.",
    duration: "4 à 5 heures",
    cost: "16 à 22 €",
    alternative: "Bus classique depuis la gare routière",
    whyNotAlternative: "Il oblige à rejoindre deux gares éloignées des centres-villes, pour quasiment le même prix.",
    bookingPlatform: "Bookaway / Marsol / Berlinas",
    bookingURL: "https://www.bookaway.com/routes/colombia/santa-marta-to-cartagena",
  },
  {
    id: 9,
    title: "Carthagène → aéroport",
    howAndWhy: "Taxi ou Uber, aéroport à une dizaine de minutes du centre.",
    duration: "15 minutes",
    cost: "4 à 6 €",
    alternative: "Aucune autre solution utile",
    whyNotAlternative: "Le taxi est déjà rapide et bon marché.",
    bookingPlatform: "Uber / taxi sur place",
    bookingURL: "https://www.uber.com/co/es/",
  },
];

/* Chaque poste budget :
   { id, category, detail, lowEstimate, highEstimate } */
const BUDGET_ITEMS = [
  {
    id: 1,
    category: "Logements",
    detail: "13 nuits (dont 2 en éco-lodge au parc Tayrona), à deux dans la chambre, prix pour une personne",
    lowEstimate: 170,
    highEstimate: 330,
  },
  {
    id: 2,
    category: "Transports",
    detail: "Bus, vol Medellín→Salento ET vol Salento→côte, colectivos et navettes",
    lowEstimate: 175,
    highEstimate: 255,
  },
  {
    id: 3,
    category: "Visites",
    detail: "Entrée Tayrona, fermes de café, guide Comuna 13, tubing à Palomino, îles Rosario (option)",
    lowEstimate: 75,
    highEstimate: 135,
  },
  {
    id: 4,
    category: "Nourriture",
    detail: "Environ 12 à 22 € par jour, pendant 14 jours",
    lowEstimate: 168,
    highEstimate: 308,
  },
  {
    id: 5,
    category: "Imprévus",
    detail: "Carte téléphone, pourboires, eau, quelques taxis",
    lowEstimate: 40,
    highEstimate: 80,
  },
];

/* Étapes de la carte (regroupements) :
   { num, key, label, days, region } */
const MAP_STAGES = [
  { num: 1, key: "medellin", label: "Medellín",                         days: "Jours 1–3",   region: "city" },
  { num: 2, key: "salento",  label: "Salento & Cocora",                 days: "Jours 4–5",   region: "coffee" },
  { num: 3, key: "coast",    label: "Côte & parcs — Minca, Tayrona, Palomino, Santa Marta", days: "Jours 6–11", region: "jungle" },
  { num: 4, key: "cartagena",label: "Carthagène",                       days: "Jours 12–14", region: "colonial" },
];

/* Infos utiles (pense-bête statique) */
const USEFUL_INFO = [
  { icon: "💲", text: "En Colombie, le symbole $ désigne le peso colombien (COP), pas le dollar. Le point sépare les milliers : $ 89.000 = 89 000 COP ≈ 20 €." },
  { icon: "🏧", text: "Aucun distributeur d'argent dans le parc Tayrona : prenez du liquide avant d'y entrer." },
  { icon: "🎫", text: "Les billets de bus achetés en ligne (redBus) doivent être imprimés avant le départ si vous partez d'un terminal physique." },
  { icon: "✈️", text: "Vérifiez toujours qu'un vol intérieur est direct avant de réserver : certaines correspondances passent par Bogotá et rallongent fortement le trajet." },
  { icon: "📅", text: "Réservez les bus et vols à l'avance en haute saison (mi-août), les places partent vite sur les lignes touristiques." },
  { icon: "🏷️", text: "Prix affichés par personne, estimations 2025-2026 à reconfirmer au moment de réserver." },
];

const TRIP_DATA = {
  regions: REGIONS,
  effort: EFFORT,
  days: TRIP_DAYS,
  legs: TRANSPORT_LEGS,
  budget: BUDGET_ITEMS,
  mapStages: MAP_STAGES,
  usefulInfo: USEFUL_INFO,
  meta: {
    title: "Colombie — Carnet de voyage",
    subtitle: "14 jours, du 13 au 26 août",
    startIso: "2025-08-13",
    endIso: "2025-08-26",
  },
};
